### ISSUE TITLE
X-axis resets improperly

### ISSUE THREAD

**Issue by wachiuphd** [andresGranadosC/GalRotpy#3]
The x-axis doesn't reset properly after making changes (I was using my own rot_curve.txt)

https://github.com/andresGranadosC/GalRotpy/blob/e0489cc767bf92be9f62d3e58304f9d7bea24da0/GalRotpy.py#L340

I believe using the code in line 446 would fix it.

https://github.com/andresGranadosC/GalRotpy/blob/e0489cc767bf92be9f62d3e58304f9d7bea24da0/GalRotpy.py#L446

**Comment by andresGranadosC** [comment]
Thank you. The line in line 446 will fix it.
