### ISSUE TITLE
<stdin> is a directory, cannot continue

### ISSUE THREAD

**Issue by RosieBraunholtz** [andresGranadosC/GalRotpy#6]
I get this error when I try to use galrotpy. Have I used the syntax correctly?

`user:~/GalrotPy$ Python3 GalRotpy.py rot_curve [disk halo] [--outfolder=<FitProfile>] `
`Python error: <stdin> is a directory, cannot continue`

**Comment by lgdonkers** [comment]
Python3 may be case sensitive, so use `python3`, and include the .txt extension on the rotation curve file (eg. `M33_rot_curve.txt`) and make sure it's in the same directory as the GalRotpy.py file. Also, for the output folder use `--outfolder=fitprofile`, without the square or angle brackets.
